# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
        poetry --version
        poetry install
    - name: Lint with flake8
      run: |
        poetry run flake8 --count --show-source --statistics
    - name: Lint with black
      run: |
        poetry run black --check src tests
    - name: Type check with mypy
      run: |
        poetry run mypy
    - name: Test with pytest
      run: |
        poetry run pytest
